server:
  port: 8082

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/


spring:
  config:
    activate:
      on-profile: default
  application:
    name: pizza-read
    zipkin:
      base-url: http://zipkin:9411
  h2:
    console:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: postgres
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher