spring:
  application:
    name: pizza-read
  cloud:
    config:
      uri: http://config-server:8888
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/