server:
  port: 9000

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: micro-usuarios
          uri: lb://usuarios
          predicates:
            - Path=/usuarios/**
        - id: micro-pizzas-read
          uri: lb://pizzas-read
          predicates:
            - Path=/pizzas-read/**
        - id: micro-pizzas-write
          uri: lb://pizzas-write
          predicates:
            - Path=/pizzas-write/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/