server:
  port: 8080


spring:
  application.name: receptor-asignador

  kafka:
    bootstrap-servers: ${kafka:localhost}:29092

    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      properties:
        key.deserializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroDeserializer
        value.deserializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroDeserializer
        schema.registry.url: http://${schema-registry:localhost}:8081

  data:
    mongodb:
      uri: mongodb://root:admin@db-receptor-asignador:27017/db_receptor_asignador?authSource=admin
      database: db_receptor_asignador
  mongo:
    database: db_receptor_asignador

