global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "config-server"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["config-server:8888"]

  - job_name: "eureka-server"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["eureka-server:8761"]

  - job_name: "pizza-read"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["pizza-read:8082"]

  - job_name: "pizza-write"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["pizza-write:8081"]

  - job_name: "usuarios"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["usuarios:8080"]

  - job_name: "gateway-server"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["gateway-server:9000"]
